name: Deploy to AWS

on:
  push:
    branches:
      - main  # only updates when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script: |
          cd /var/www/webdeveloper
          git reset --hard origin/main
          git pull origin main
          npm install
          npm run build
          pm2 restart all
